{-# LANGUAGE DataKinds #-}
{-# LANGUAGE StandaloneKindSignatures #-}
{-# LANGUAGE TypeData #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -Wno-redundant-constraints #-}
{-# OPTIONS_HADDOCK hide #-}

module Control.Monad.Borrow.Pure.Lifetime.Internal (
  module Control.Monad.Borrow.Pure.Lifetime.Internal,
) where

import Control.DeepSeq (NFData (..))
import Data.Kind
import GHC.TypeLits hiding (type (<=))

infixr 3 /\, :/\

-- | The meet of the two lifetimes. It is the longest lifetime that is shorter than both of them.
type (/\) = (:/\)

-- NOTE:  We want to use @TypeData@ extension for Lifetime, but it makes Haddock panic!

-- Lifetime is a free bounded lower semilattice generated by atomic lifetimes.

-- | The kind (type) of lifetimes.
data Lifetime = Al Nat | Lifetime :/\ Lifetime | Static

type Al = 'Al

-- | 'Static' lifetime, which lives forever and 'Control.Monad.Borrow.Pure.Lifetime.Token.neverEnds'.
type Static = 'Static

infix 2 <=, <=!, <=!!

type Witness :: Lifetime -> Lifetime -> Type
data Witness a b where
  Inf :: Witness a b -> Witness a c -> Witness a (b /\ c)
  Top :: Witness a Static
  Inherit' :: Witness' a b -> Witness a b

instance NFData (Witness a b) where
  rnf (Inf a b) = rnf a `seq` rnf b
  rnf Top = ()
  rnf (Inherit' w) = rnf w

deriving instance Show (Witness a b)

type Witness' :: Lifetime -> Lifetime -> Type
data Witness' a b where
  AssocR :: Witness' (a /\ (b /\ c)) d -> Witness' ((a /\ b) /\ c) d
  Inherit'' :: Witness'' a b -> Witness' a b

instance NFData (Witness' a b) where
  rnf (AssocR w) = rnf w
  rnf (Inherit'' w) = rnf w

deriving instance Show (Witness' a b)

type Witness'' :: Lifetime -> Lifetime -> Type
data Witness'' a b where
  Reflect :: Witness'' a a
  InfL :: Witness'' (a /\ b) a
  InfIntroL :: Witness' b c -> Witness'' (a /\ b) c

instance NFData (Witness'' a b) where
  rnf Reflect = ()
  rnf InfL = ()
  rnf (InfIntroL w) = rnf w

deriving instance Show (Witness'' a b)

{- | @α@ ends no later than @β@.

The safe modules export only its synonym '(<=)', so no instance can be written against them.
-}
type SubLifetime :: Lifetime -> Lifetime -> Constraint
class SubLifetime α β where
  -- | The witness of the relation.
  witness :: Witness α β

{- | @α <= β@: the lifetime @α@ ends no later than @β@, so anything valid for @β@ is valid for @α@.

It is a synonym, so that the safe modules can export it without letting anyone write an instance; GHC's messages name the class behind it, @SubLifetime@.
The library derives it from these rules: every lifetime ends no later than itself and than 'Static'; @α /\\ β@ ends no later than @α@ and than @β@; and @α@ ends no later than @β /\\ γ@ when it ends no later than both.
It does not chain hypotheses: from @α >= β@ and @β >= γ@ in a signature it does not derive @α >= γ@, and GHC reports that it could not deduce @γ <=!! α@; add @α >= γ@ to the signature.
In general, when GHC asks for a constraint such as @β <=!! α@, which the safe modules do not name, add @α >= β@ to the signature.
When GHC instead reports overlapping instances for @SubLifetime@ with a lifetime it made up, such as @α0@, it cannot tell which lifetime is meant: with @step :: (α >= β) => Share α Int -> Share β Int@, the intermediate one of @step (step s)@, say, or one that occurs only in constraints.
Name that lifetime with a type application, as in @step \@α \@γ (step \@α \@α s)@, or drop the constraints on a lifetime that does not occur in the type.
-}
type (<=) :: Lifetime -> Lifetime -> Constraint
type (<=) = SubLifetime

-- | Flipped version of '<='.
type (>=) :: Lifetime -> Lifetime -> Constraint
type α >= β = β <= α

instance (α <= β, α <= γ) => SubLifetime α (β /\ γ) where
  witness = Inf witness witness
  {-# NOINLINE witness #-}

instance SubLifetime α Static where
  witness = Top
  {-# NOINLINE witness #-}

instance {-# INCOHERENT #-} (α <=! β) => SubLifetime α β where
  witness = Inherit' witness'
  {-# NOINLINE witness #-}

type (<=!) :: Lifetime -> Lifetime -> Constraint
class α <=! β where
  -- | The witness of the relation.
  witness' :: Witness' α β

instance (α /\ (β /\ γ) <=! δ) => (α /\ β) /\ γ <=! δ where
  witness' = AssocR witness'
  {-# NOINLINE witness' #-}

instance {-# INCOHERENT #-} (α <=!! β) => α <=! β where
  witness' = Inherit'' witness''
  {-# NOINLINE witness' #-}

type (<=!!) :: Lifetime -> Lifetime -> Constraint
class α <=!! β where
  -- | The witness of the relation.
  witness'' :: Witness'' α β

instance α <=!! α where
  witness'' = Reflect
  {-# NOINLINE witness'' #-}

instance α /\ β <=!! α where
  witness'' = InfL
  {-# NOINLINE witness'' #-}

{-
instance α /\ β <=!! β where
  witness'' = Witness -}

instance {-# INCOHERENT #-} (β <=! γ) => α /\ β <=!! γ where
  witness'' = InfIntroL witness'
  {-# NOINLINE witness'' #-}
